// Endpoint catalogue for the modules outside the foundation and time
// specifications. Each entry: method, path, summary, tag, and the permission
// or authentication it needs. The OpenAPI document is generated from it.
type Entry = [
  "get" | "post" | "put" | "delete",
  string,
  string,
  string,
  string,
];
const e = (
  method: Entry[0],
  path: string,
  summary: string,
  tag: string,
  access: string,
): Entry => [method, path, summary, tag, access];

export const moduleEndpoints: Entry[] = [
  e(
    "get",
    "/workforce/jobs",
    "Company jobs (Basic+)",
    "Workforce",
    "attendance.self or attendance.manage",
  ),
  e("post", "/workforce/jobs", "Create job", "Workforce", "attendance.manage"),
  e(
    "put",
    "/workforce/jobs/{id}",
    "Edit or archive job",
    "Workforce",
    "attendance.manage",
  ),
  e(
    "get",
    "/workforce/logs",
    "Own or company job timesheets (?from, to)",
    "Workforce",
    "attendance.self or attendance.manage",
  ),
  e(
    "post",
    "/workforce/logs/start",
    "Start own job timer while checked in",
    "Workforce",
    "attendance.self",
  ),
  e(
    "post",
    "/workforce/logs/stop",
    "Stop own job timer",
    "Workforce",
    "attendance.self",
  ),
  e(
    "get",
    "/workforce/assignments",
    "Assigned activities (Advanced+; ?from, to)",
    "Workforce",
    "attendance.self or attendance.manage",
  ),
  e(
    "post",
    "/workforce/assignments",
    "Schedule employee job activity",
    "Workforce",
    "attendance.manage",
  ),
  e(
    "put",
    "/workforce/assignments/{id}",
    "Reschedule job activity",
    "Workforce",
    "attendance.manage",
  ),
  e(
    "put",
    "/workforce/assignments/{id}/progress",
    "Update own activity progress; HR may cancel",
    "Workforce",
    "attendance.self or attendance.manage",
  ),
  e(
    "get",
    "/workforce/agencies",
    "Contractor agencies (Advanced+)",
    "Workforce",
    "employees.write",
  ),
  e(
    "post",
    "/workforce/agencies",
    "Create contractor agency",
    "Workforce",
    "employees.write",
  ),
  e(
    "put",
    "/workforce/agencies/{id}",
    "Edit contractor agency",
    "Workforce",
    "employees.write",
  ),
  e(
    "get",
    "/workforce/contracts",
    "Employee agency contracts (Advanced+)",
    "Workforce",
    "employees.write",
  ),
  e(
    "post",
    "/workforce/contracts",
    "Create employee agency contract",
    "Workforce",
    "employees.write",
  ),
  e(
    "put",
    "/workforce/contracts/{id}",
    "Edit or end agency contract",
    "Workforce",
    "employees.write",
  ),
  e(
    "get",
    "/workforce/breaks",
    "Own recent unpaid breaks",
    "Workforce",
    "attendance.self",
  ),
  e(
    "post",
    "/workforce/breaks/start",
    "Start unpaid break; stop job timer",
    "Workforce",
    "attendance.self",
  ),
  e(
    "post",
    "/workforce/breaks/stop",
    "End unpaid break",
    "Workforce",
    "attendance.self",
  ),
  e(
    "get",
    "/workforce/sites",
    "Multi-site attendance dashboard (?date)",
    "Workforce",
    "attendance.read",
  ),
  // Payroll
  e(
    "get",
    "/payroll/statutory",
    "Effective statutory settings and pay rules",
    "Payroll",
    "payroll.read",
  ),
  e(
    "put",
    "/payroll/statutory",
    "Save statutory settings and pay rules",
    "Payroll",
    "payroll.manage",
  ),
  e(
    "get",
    "/payroll/statutory-rules",
    "Platform and company statutory rules for a month (?period=YYYY-MM)",
    "Payroll",
    "payroll.read",
  ),
  e(
    "post",
    "/payroll/statutory-rules",
    "Add an effective-dated company rule",
    "Payroll",
    "payroll.manage",
  ),
  e(
    "put",
    "/payroll/statutory-rules/{id}",
    "Change a company rule",
    "Payroll",
    "payroll.manage",
  ),
  e(
    "get",
    "/payroll/structures",
    "Employees with salary structures",
    "Payroll",
    "payroll.read",
  ),
  e(
    "put",
    "/payroll/structures/{id}",
    "Set an employee's salary structure",
    "Payroll",
    "payroll.manage",
  ),
  e("get", "/payroll/loans", "Loans and advances", "Payroll", "payroll.read"),
  e(
    "post",
    "/payroll/loans",
    "Record a loan or advance",
    "Payroll",
    "payroll.manage",
  ),
  e(
    "put",
    "/payroll/loans/{id}",
    "Change instalment or status",
    "Payroll",
    "payroll.manage",
  ),
  e("get", "/payroll/runs", "Payroll runs", "Payroll", "payroll.read"),
  e(
    "post",
    "/payroll/runs",
    "Calculate a draft run for a month",
    "Payroll",
    "payroll.manage",
  ),
  e("get", "/payroll/runs/{id}", "Run with lines", "Payroll", "payroll.read"),
  e(
    "delete",
    "/payroll/runs/{id}",
    "Delete a draft run",
    "Payroll",
    "payroll.manage",
  ),
  e(
    "post",
    "/payroll/runs/{id}/recalculate",
    "Recalculate a draft",
    "Payroll",
    "payroll.manage",
  ),
  e(
    "put",
    "/payroll/runs/{id}/items/{itemId}",
    "Adjust LOP, bonus, incentive, other earnings or deductions",
    "Payroll",
    "payroll.manage",
  ),
  e(
    "post",
    "/payroll/runs/{id}/submit",
    "Submit for approval (locks the month)",
    "Payroll",
    "payroll.manage",
  ),
  e(
    "post",
    "/payroll/runs/{id}/approve",
    "Approve (not the submitter)",
    "Payroll",
    "payroll.approve",
  ),
  e(
    "post",
    "/payroll/runs/{id}/reject",
    "Send back to draft with a note",
    "Payroll",
    "payroll.approve",
  ),
  e(
    "post",
    "/payroll/runs/{id}/process",
    "Process an approved run and issue payslips",
    "Payroll",
    "payroll.manage",
  ),
  e(
    "get",
    "/payroll/runs/{id}/reports/{report}",
    "PF ECR, ESI, PT, TDS or salary register",
    "Payroll",
    "payroll.read",
  ),
  e(
    "get",
    "/payroll/payslips",
    "Payslips (own with payroll.self)",
    "Payroll",
    "payroll.read or payroll.self",
  ),
  e(
    "get",
    "/payroll/payslips/{id}/pdf",
    "Payslip PDF",
    "Payroll",
    "payroll.read or own payslip",
  ),
  // Expenses
  e(
    "get",
    "/expenses/categories",
    "Expense categories",
    "Expenses",
    "expenses.self",
  ),
  e(
    "post",
    "/expenses/categories",
    "Add a category",
    "Expenses",
    "expenses.manage",
  ),
  e(
    "post",
    "/expenses/categories/defaults",
    "Add the standard categories",
    "Expenses",
    "expenses.manage",
  ),
  e(
    "get",
    "/expenses/claims",
    "Claims (?scope=own|team|company&status=)",
    "Expenses",
    "expenses.self",
  ),
  e(
    "post",
    "/expenses/claims",
    "Submit a claim with receipt",
    "Expenses",
    "expenses.self",
  ),
  e(
    "put",
    "/expenses/claims/{id}",
    "Approve, reject, cancel or mark paid",
    "Expenses",
    "manager, finance or owner",
  ),
  e(
    "get",
    "/expenses/claims/{id}/receipt",
    "Receipt file",
    "Expenses",
    "owner or reviewer",
  ),
  // Assets
  e(
    "get",
    "/assets",
    "Asset register (filters: status, category, q, warrantyWithin)",
    "Assets",
    "assets.manage",
  ),
  e("post", "/assets", "Add an asset", "Assets", "assets.manage"),
  e("put", "/assets/{id}", "Edit an asset", "Assets", "assets.manage"),
  e("get", "/assets/{id}", "Asset with history", "Assets", "assets.manage"),
  e(
    "post",
    "/assets/{id}/assign",
    "Issue to an employee",
    "Assets",
    "assets.manage",
  ),
  e(
    "post",
    "/assets/{id}/return",
    "Record a return with condition",
    "Assets",
    "assets.manage",
  ),
  e(
    "post",
    "/assets/{id}/status",
    "Repair, retire, lost or back in stock",
    "Assets",
    "assets.manage",
  ),
  e("get", "/assets/mine", "Assets issued to me", "Assets", "assets.self"),
  e(
    "post",
    "/assets/assignments/{id}/acknowledge",
    "Acknowledge receipt",
    "Assets",
    "assets.self",
  ),
  // Training
  e("get", "/training/courses", "Courses", "Training", "training.self"),
  e("post", "/training/courses", "Add a course", "Training", "training.manage"),
  e("get", "/training/trainers", "Trainers", "Training", "training.manage"),
  e(
    "get",
    "/training/sessions",
    "Sessions (open and own for employees)",
    "Training",
    "training.self",
  ),
  e(
    "post",
    "/training/sessions",
    "Schedule a session",
    "Training",
    "training.manage",
  ),
  e(
    "post",
    "/training/sessions/{id}/enrollments",
    "Enroll employees",
    "Training",
    "training.manage",
  ),
  e(
    "post",
    "/training/sessions/{id}/join",
    "Join an open session",
    "Training",
    "training.self",
  ),
  e(
    "put",
    "/training/enrollments/{id}",
    "Mark attendance",
    "Training",
    "training.manage",
  ),
  e(
    "post",
    "/training/enrollments/{id}/result",
    "Record score and pass",
    "Training",
    "training.manage",
  ),
  e(
    "get",
    "/training/enrollments/{id}/certificate",
    "Certificate PDF",
    "Training",
    "training.manage or own",
  ),
  e(
    "get",
    "/training/certifications",
    "Certificates (?expiringWithin=days)",
    "Training",
    "training.self",
  ),
  e(
    "get",
    "/training/compliance",
    "Mandatory-course compliance",
    "Training",
    "training.manage",
  ),
  e("get", "/training/skills", "Skills register", "Training", "training.self"),
  e(
    "get",
    "/training/mine",
    "My training summary",
    "Training",
    "training.self",
  ),
  // Recruitment
  e(
    "get",
    "/recruitment/jobs",
    "Job openings",
    "Recruitment",
    "recruitment.manage",
  ),
  e(
    "post",
    "/recruitment/jobs",
    "Create a job opening",
    "Recruitment",
    "recruitment.manage",
  ),
  e(
    "get",
    "/recruitment/candidates",
    "Candidate database (?jobId&stage&q)",
    "Recruitment",
    "recruitment.manage",
  ),
  e(
    "post",
    "/recruitment/candidates/{id}/stage",
    "Move pipeline stage",
    "Recruitment",
    "recruitment.manage",
  ),
  e(
    "post",
    "/recruitment/candidates/{id}/offers",
    "Prepare an offer",
    "Recruitment",
    "recruitment.manage",
  ),
  e(
    "post",
    "/recruitment/offers/{id}/send",
    "Send the private offer link",
    "Recruitment",
    "recruitment.manage",
  ),
  e(
    "get",
    "/recruitment/offers/{id}/letter",
    "Offer letter PDF",
    "Recruitment",
    "recruitment.manage",
  ),
  e(
    "post",
    "/recruitment/candidates/{id}/hire",
    "Hire (accepted offer required)",
    "Recruitment",
    "recruitment.manage",
  ),
  e(
    "get",
    "/recruitment/careers",
    "Careers page settings",
    "Recruitment",
    "recruitment.manage",
  ),
  e(
    "get",
    "/public/careers/{companyCode}",
    "Public open jobs",
    "Public",
    "none",
  ),
  e(
    "post",
    "/public/careers/{companyCode}/jobs/{jobId}/apply",
    "Public application with PDF resume and consent",
    "Public",
    "none (rate-limited)",
  ),
  e(
    "get",
    "/public/offers/{token}",
    "Candidate views an offer",
    "Public",
    "private link",
  ),
  e(
    "post",
    "/public/offers/{token}",
    "Candidate accepts or declines",
    "Public",
    "private link",
  ),
  // Performance
  e(
    "get",
    "/performance/cycles",
    "Review cycles",
    "Performance",
    "performance.self",
  ),
  e(
    "post",
    "/performance/cycles",
    "Create a cycle (scale, labels, peers)",
    "Performance",
    "performance.manage",
  ),
  e(
    "get",
    "/performance/goals",
    "Goals (KPI, OKR, key results)",
    "Performance",
    "performance.self",
  ),
  e(
    "get",
    "/performance/reviews/{id}",
    "Review with peer summary",
    "Performance",
    "reviewer, HR or employee",
  ),
  e(
    "post",
    "/performance/reviews/{id}/peers",
    "Request peer reviews",
    "Performance",
    "reviewer or HR",
  ),
  e(
    "post",
    "/performance/reviews/{id}/calibrate",
    "Calibrate the final rating",
    "Performance",
    "performance.manage",
  ),
  e(
    "get",
    "/performance/peer-reviews",
    "Peer reviews asked of me",
    "Performance",
    "performance.self",
  ),
  e(
    "get",
    "/performance/history",
    "Ratings across cycles",
    "Performance",
    "performance.self",
  ),
  // Documents, helpdesk, onboarding, notifications
  e(
    "get",
    "/documents",
    "Documents (?scope=own|policies|company)",
    "Documents",
    "documents.self",
  ),
  e(
    "get",
    "/documents/{id}/download",
    "Signed download link",
    "Documents",
    "documents.self",
  ),
  e("get", "/helpdesk", "HR requests", "Helpdesk", "helpdesk.self"),
  e("post", "/helpdesk", "Raise an HR request", "Helpdesk", "helpdesk.self"),
  e("get", "/onboarding", "Onboardings", "Onboarding", "onboarding.manage"),
  e("get", "/notifications", "My notifications", "Notifications", "signed in"),
  e(
    "get",
    "/notifications/templates",
    "Templates per event and channel",
    "Notifications",
    "notifications.manage",
  ),
  e(
    "put",
    "/notifications/templates",
    "Save a template (IN_APP, EMAIL, SMS, WHATSAPP)",
    "Notifications",
    "notifications.manage",
  ),
  // AI
  e(
    "post",
    "/ai/query",
    "Ask HR Copilot (read-only intent catalogue)",
    "AI",
    "ai.use",
  ),
  e(
    "post",
    "/ai/generate",
    "Generate a draft",
    "AI",
    "ai.use plus kind permission",
  ),
  e("get", "/ai/documents", "Saved drafts", "AI", "ai.use"),
  // Mobile (bearer token from /v1/auth/login)
  e("post", "/v1/auth/login", "Mobile sign-in with device", "Mobile", "none"),
  e(
    "post",
    "/v1/auth/refresh",
    "Refresh mobile tokens",
    "Mobile",
    "refresh token",
  ),
  e("get", "/v1/home", "Dashboard", "Mobile", "bearer"),
  e(
    "get",
    "/v1/approvals",
    "Leave and expense items to decide",
    "Mobile",
    "bearer",
  ),
  e(
    "post",
    "/v1/attendance/check-in",
    "GPS check-in",
    "Mobile",
    "attendance.self",
  ),
  e(
    "post",
    "/v1/attendance/face-punch",
    "Face attendance",
    "Mobile",
    "attendance.self",
  ),
  e("post", "/v1/push-token", "Register a push token", "Mobile", "bearer"),
  e("get", "/v1/payslips/{id}/pdf", "Payslip PDF", "Mobile", "own payslip"),
  // Public API (API key: X-API-Key or Bearer hrms_...)
  e("get", "/v1/employees", "Employees", "Public API", "employees.read"),
  e(
    "post",
    "/v1/employees",
    "Create an employee",
    "Public API",
    "employees.write",
  ),
  e(
    "put",
    "/v1/employees/{id}",
    "Update an employee",
    "Public API",
    "employees.write",
  ),
  e(
    "get",
    "/v1/attendance",
    "Attendance (from, to, updatedSince)",
    "Public API",
    "attendance.read",
  ),
  e(
    "post",
    "/v1/attendance",
    "Record attendance (work date and local times)",
    "Public API",
    "attendance.write",
  ),
  e("get", "/v1/leave", "Leave requests", "Public API", "leave.read"),
  e(
    "put",
    "/v1/leave/{id}",
    "Approve or reject leave",
    "Public API",
    "leave.write",
  ),
  e("get", "/v1/payslips", "Payslips", "Public API", "payroll.read"),
  e(
    "get",
    "/v1/accounting-journal",
    "Payroll journal (from, to)",
    "Public API",
    "payroll.read",
  ),
  // Integrations
  e(
    "get",
    "/integrations",
    "Integrations, API keys and webhooks",
    "Integrations",
    "integrations.manage",
  ),
  e(
    "get",
    "/integrations/accounting-export",
    "Accounting journal as CSV, XLSX or JSON",
    "Integrations",
    "integrations.manage",
  ),
];

const ok = {
  description: "Successful response",
  content: { "application/json": { schema: { type: "object" } } },
};
const err = {
  description: "Error",
  content: {
    "application/json": { schema: { $ref: "#/components/schemas/Error" } },
  },
};
export function modulePaths() {
  const paths: Record<string, Record<string, unknown>> = {};
  for (const [method, path, summary, tag, access] of moduleEndpoints) {
    const params = [...path.matchAll(/\{(\w+)\}/g)].map((m) => ({
      name: m[1],
      in: "path",
      required: true,
      schema: { type: "string" },
    }));
    const security = path.startsWith("/public/")
      ? []
      : tag === "Public API"
        ? [{ apiKey: [] }]
        : tag === "Mobile"
          ? [{ bearer: [] }]
          : [{ accessCookie: [] }, { bearer: [] }];
    paths[path] = {
      ...paths[path],
      [method]: {
        summary,
        description: `Access: ${access}.`,
        tags: [tag],
        security,
        ...(params.length ? { parameters: params } : {}),
        ...(["post", "put"].includes(method)
          ? {
              requestBody: {
                content: { "application/json": { schema: { type: "object" } } },
              },
            }
          : {}),
        responses: {
          "200": ok,
          "401": err,
          "403": err,
          "404": err,
          "409": err,
          "422": err,
        },
      },
    };
  }
  return paths;
}
