export const permissions = {
  "ai.use": "Use HR Copilot with existing data permissions",
  "ai.configure": "Configure company AI processing and retention",
  "ai.recruitment": "Draft and review job descriptions and interview notes",
  "ai.performance": "Draft and approve performance suggestions",
  "ai.documents": "Draft and approve employee letters",
  "ai.reports": "Summarize reports permitted by existing permissions",
  "attendance.team.read": "View direct reports' attendance through HR Copilot",
  "timeoff.team.read": "View direct reports' leave through HR Copilot",
  "dashboard.read": "View company dashboard",
  "company.read": "View company settings",
  "company.write": "Edit company settings",
  "users.read": "View users and sessions",
  "users.write": "Create and manage users",
  "roles.read": "View roles and permissions",
  "roles.write": "Configure roles and permissions",
  "employees.read": "View employee records",
  "employees.write": "Create, edit and archive employees",
  "employees.sensitive": "Read and edit encrypted identity and bank details",
  "organization.read": "View departments, designations and branches",
  "organization.write": "Manage departments, designations and branches",
  "profile.read": "View own employee profile",
  "profile.write": "Update permitted personal fields",
  "audit.read": "View company audit trail",
  "attendance.self": "Check in/out and view own attendance",
  "attendance.read": "View company attendance reports",
  "attendance.manage": "Correct and import company attendance",
  "timeoff.self": "Request leave and view own balances",
  "timeoff.manage": "Review company leave requests",
  "payroll.self": "View and download own payslips",
  "payroll.read": "View company payslips",
  "payroll.manage": "Create and manage payslips",
  "payroll.approve": "Approve reviewed payroll runs for processing",
  "time.configure": "Manage shifts, holidays, leave types and geofencing",
  "fieldtracking.read": "View live locations for permitted field employees",
  "fieldtracking.manage": "Configure and stop field tracking sessions",
  "devices.manage": "View, deactivate and sign out company mobile devices",
  "integrations.manage":
    "Manage integrations, API keys, webhooks and accounting exports",
  "security.manage": "Configure MFA, lockout and session security policies",
  "support.use": "Create and follow company support tickets",
  "recruitment.manage": "Manage job openings, candidates and hiring",
  "recruitment.interview": "View assigned interviews and submit feedback",
  "performance.manage":
    "Manage review cycles, goals and reviews for all employees",
  "performance.team": "Set goals and review direct reports",
  "performance.self": "View own goals and complete self reviews",
  "expenses.self": "Submit and track own expense claims",
  "training.manage":
    "Manage courses, trainers, sessions, enrollment, certifications and skills",
  "assets.manage": "Manage the asset register, issue and return assets",
  "assets.self": "View assets issued to me and acknowledge receipt",
  "training.self":
    "View own training, certifications and skills, and join open sessions",
  "expenses.approve": "Approve direct reports' expense claims",
  "expenses.manage": "Manage expense categories, approvals and reimbursements",
  "reports.custom": "Build and run custom reports on permitted data",
  "documents.self": "Upload and view own documents and company policies",
  "documents.manage": "Manage all employee and company documents",
  "helpdesk.self": "Raise and follow own HR helpdesk tickets",
  "helpdesk.manage": "Work HR helpdesk tickets for the company",
  "onboarding.manage": "Run new-joiner onboarding",
  "announcements.manage": "Publish company announcements",
  "notifications.manage": "Edit notification and email templates",
} as const;
export type PermissionKey = keyof typeof permissions;
export const roleNames = [
  "Super Admin",
  "SaaS Admin",
  "Company Owner",
  "Company Admin",
  "HR Manager",
  "HR Executive",
  "Payroll Manager",
  "Finance Manager",
  "Department Manager",
  "Team Leader",
  "Employee",
  "Recruiter",
  "Auditor",
] as const;
const self: PermissionKey[] = [
  "ai.use",
  "profile.read",
  "profile.write",
  "attendance.self",
  "timeoff.self",
  "payroll.self",
  "performance.self",
  "expenses.self",
  "training.self",
  "assets.self",
  "documents.self",
  "helpdesk.self",
];
export const defaultGrants: Record<
  (typeof roleNames)[number],
  PermissionKey[]
> = {
  "Super Admin": Object.keys(permissions) as PermissionKey[],
  "Company Owner": Object.keys(permissions) as PermissionKey[],
  "Company Admin": Object.keys(permissions) as PermissionKey[],
  // Provider staff: platform access comes from the provider company, not grants.
  "SaaS Admin": [
    "dashboard.read",
    "company.read",
    "audit.read",
    "support.use",
    "profile.read",
    "profile.write",
    "documents.self",
    "helpdesk.self",
  ],
  "HR Manager": [
    "training.manage",
    "assets.manage",
    "documents.manage",
    "helpdesk.manage",
    "onboarding.manage",
    "announcements.manage",
    "notifications.manage",
    "recruitment.manage",
    "recruitment.interview",
    "performance.manage",
    "performance.team",
    "expenses.approve",
    "expenses.manage",
    "reports.custom",
    "devices.manage",
    "support.use",
    "payroll.read",
    "payroll.manage",
    "fieldtracking.read",
    "fieldtracking.manage",
    "ai.recruitment",
    "ai.performance",
    "ai.documents",
    "ai.reports",
    "attendance.read",
    "attendance.manage",
    "timeoff.manage",
    "time.configure",
    "dashboard.read",
    "employees.read",
    "employees.write",
    "employees.sensitive",
    "organization.read",
    "organization.write",
    "company.read",
    "audit.read",
    ...self,
  ],
  "HR Executive": [
    "training.manage",
    "assets.manage",
    "documents.manage",
    "helpdesk.manage",
    "onboarding.manage",
    "announcements.manage",
    "recruitment.manage",
    "recruitment.interview",
    "fieldtracking.read",
    "attendance.read",
    "attendance.manage",
    "timeoff.manage",
    "dashboard.read",
    "employees.read",
    "employees.write",
    "organization.read",
    ...self,
  ],
  "Payroll Manager": [
    "expenses.manage",
    "reports.custom",
    "payroll.read",
    "payroll.manage",
    "attendance.read",
    "employees.read",
    "employees.sensitive",
    "organization.read",
    ...self,
  ],
  "Finance Manager": [
    "expenses.manage",
    "reports.custom",
    "payroll.read",
    "payroll.manage",
    "payroll.approve",
    "dashboard.read",
    "employees.read",
    "organization.read",
    ...self,
  ],
  "Department Manager": [
    ...self,
    "performance.team",
    "expenses.approve",
    "recruitment.interview",
    "attendance.team.read",
    "timeoff.team.read",
    "fieldtracking.read",
    "ai.performance",
  ],
  "Team Leader": [
    ...self,
    "performance.team",
    "expenses.approve",
    "recruitment.interview",
    "attendance.team.read",
    "timeoff.team.read",
    "fieldtracking.read",
    "ai.performance",
  ],
  Employee: [...self],
  Recruiter: [
    "organization.read",
    "ai.recruitment",
    "recruitment.manage",
    "recruitment.interview",
    "onboarding.manage",
    ...self,
  ],
  Auditor: [
    "reports.custom",
    "attendance.read",
    "dashboard.read",
    "employees.read",
    "organization.read",
    "company.read",
    "audit.read",
    ...self,
  ],
};
// Accounts that only a Super Admin or Company Owner may change or reset.
export const protectedRoles = ["Super Admin", "Company Owner", "Company Admin"];
export function can(grants: readonly string[], permission: string) {
  return grants.includes(permission);
}
