"use client";
import { useEffect, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { api } from "@/lib/api-client";
import type { Me } from "@/types/ui";
import { Button } from "./ui/button";
import { documentKinds, letterKinds, messageKinds, type DraftInput, type QueryResult } from "@/modules/ai/contracts";

type Doc = { id: string; kind: DraftInput["kind"]; title: string; content: string; status: string; revision: number; input?: DraftInput };
type Config = { enabled: boolean; allowExternalProcessing: boolean; retentionDays: number; providerConfigured: boolean; localProvider: boolean };
const names = { job_description: "Job description", interview_questions: "Interview questions", interview_summary: "Interview summary", performance: "Performance assistant", letter: "HR letter", report_summary: "Report summary", candidate_summary: "Candidate summary", candidate_message: "Candidate message", review_draft: "Review and development plan" };
const permission = { job_description: "ai.recruitment", interview_questions: "ai.recruitment", interview_summary: "ai.recruitment", performance: "ai.performance", letter: "ai.documents", report_summary: "ai.reports", candidate_summary: "ai.recruitment", candidate_message: "ai.recruitment", review_draft: "ai.performance" };

function Answer({ result }: { result: QueryResult }) {
  return <div className="space-y-4"><p className="whitespace-pre-wrap">{result.answer}</p>
    {result.columns.length > 0 && <div className="table-scroll"><table><thead><tr>{result.columns.map(c => <th key={c}>{c}</th>)}</tr></thead><tbody>{result.rows.map((row, i) => <tr key={i}>{row.map((value, j) => <td key={j}>{value}</td>)}</tr>)}</tbody></table>{!result.rows.length && <p className="empty">No matching records.</p>}</div>}
    {result.truncated && <p className="text-sm muted">Showing the first 200 rows.</p>}
    <p className="text-xs muted">Scope: {result.scope} · {result.asOf} · Sources: {result.sources.join(", ") || "Product guidance"}</p>
  </div>;
}
export function HRCopilot({ me }: { me: Me }) {
  const client = useQueryClient();
  const [tab, setTab] = useState("chat"), [question, setQuestion] = useState("");
  const [result, setResult] = useState<QueryResult | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const [draft, setDraft] = useState<Doc | null>(null);
  const kinds = documentKinds.filter(k => me.permissions.includes(permission[k]));
  const [kind, setKind] = useState<DraftInput["kind"]>(kinds[0] || "job_description");
  const [notes, setNotes] = useState([{ question: "", answer: "", rating: 3, comments: "" }]);
  const [reviewed, setReviewed] = useState(false);
  const config = useQuery({ queryKey: ["ai", "settings"], queryFn: () => api<Config>("ai/settings") });
  const docs = useQuery({ queryKey: ["ai", "documents"], queryFn: () => api<Doc[]>("ai/documents"), enabled: !!kinds.length });
  const people = useQuery({ queryKey: ["ai", "employees"], queryFn: () => api<{ id: string; firstName: string; lastName: string; employeeCode: string }[]>("ai/employees"), enabled: me.permissions.includes("ai.documents") || me.permissions.includes("ai.performance") });
  const candidates = useQuery({ queryKey: ["ai", "candidates"], queryFn: () => api<{ id: string; name: string; stage: string; job: { title: string } }[]>("recruitment/candidates"), enabled: kind.startsWith("candidate_") && me.permissions.includes("recruitment.manage") });
  const reviews = useQuery({ queryKey: ["ai", "reviews"], queryFn: () => api<{ id: string; status: string; employee: { firstName: string; lastName: string; employeeCode: string }; cycle: { name: string } }[]>(`performance/reviews?scope=${me.permissions.includes("performance.manage") ? "company" : "team"}`), enabled: kind === "review_draft" });
  const history = useQuery({ queryKey: ["ai", "conversations"], queryFn: () => api<{ id: string; createdAt: string; messages: { role: string; content: string }[] }[]>("ai/conversations") });
  const logs = useQuery({ queryKey: ["ai", "logs"], queryFn: () => api<{ id: string; intent: string; status: string; timestamp: string; dataSources: string[] }[]>("ai/logs"), enabled: tab === "logs" && me.permissions.includes("audit.read") });
  useEffect(() => { if (new URLSearchParams(window.location.search).has("report") && me.permissions.includes("ai.reports")) { setTab("drafts"); setKind("report_summary"); } }, [me.permissions]);
  async function run(work: () => Promise<void>) { setBusy(true); setError(""); try { await work(); await client.invalidateQueries({ queryKey: ["ai"] }); } catch (e) { setError(e instanceof Error ? e.message : "Request failed."); } finally { setBusy(false); } }
  const available = config.data?.enabled && config.data.providerConfigured && (config.data.localProvider || config.data.allowExternalProcessing);
  async function generate(input: DraftInput) { const doc = await api<Doc>("ai/generate", { method: "POST", body: JSON.stringify(input) }); setDraft({ ...doc, input }); setReviewed(false); }
  async function save(action: "save" | "approve" | "publish") { if (!draft) return; const doc = await api<Doc>(`ai/documents/${draft.id}`, { method: "PUT", body: JSON.stringify({ title: draft.title, content: draft.content, revision: draft.revision, action }) }); setDraft({ ...doc, input: draft.input }); setReviewed(false); }
  const presets = ["What is my leave balance?", "When did I check in today?", "Show my attendance this month.", "How many holidays are remaining?", ...(me.permissions.includes("attendance.team.read") ? ["Show my team's attendance.", "Who is absent in my team today?"] : []), ...(me.permissions.includes("attendance.read") ? ["Show employees who were late more than 3 times this month.", "Summarize this month's attendance."] : [])];
  return <>
    <div className="page-heading"><div><div className="eyebrow mb-3">People assistance</div><h1>HR Copilot</h1><p>Ask about permitted HR records, draft content and review suggestions.</p></div></div>
    <div className="section-tabs">{["chat", ...(kinds.length ? ["drafts"] : []), ...(me.permissions.includes("ai.configure") ? ["settings"] : []), ...(me.permissions.includes("audit.read") ? ["logs"] : [])].map(value => <button key={value} className={tab === value ? "active" : ""} onClick={() => { setTab(value); setError(""); }}>{value === "chat" ? "Ask HR Copilot" : value === "drafts" ? "AI assistants" : value === "logs" ? "Access logs" : "AI settings"}</button>)}</div>
    {(error || config.error) && <div role="alert" className="error mb-4">{error || config.error?.message}</div>}
    {!available && <p className="card p-4 mb-4 text-sm">AI generation is unavailable until your administrator configures a provider and enables processing. Supported record questions still use the secure read-only query engine.</p>}
    {tab === "chat" && <div className="grid gap-6 lg:grid-cols-[1fr_260px]"><section className="card p-6 space-y-5">
      <div className="flex flex-wrap gap-2">{presets.map(p => <Button key={p} variant="outline" size="sm" disabled={busy} onClick={() => setQuestion(p)}>{p}</Button>)}</div>
      <form onSubmit={event => { event.preventDefault(); void run(async () => { setResult(null); setResult(await api<QueryResult>("ai/query", { method: "POST", body: JSON.stringify({ question }) })); }); }} className="space-y-3">
        <label>Your HR question<textarea rows={3} value={question} maxLength={1000} minLength={3} required onChange={e => setQuestion(e.target.value)} placeholder="Show my attendance this month" /></label>
        <p className="text-xs muted">Use Today or This month. Do not enter bank details, identity numbers, passwords or confidential notes. Follow-up questions should include their full context.</p>
        <Button disabled={busy}>{busy ? "Working..." : "Ask Copilot"}</Button>
      </form>
      {result && <Answer result={result} />}
    </section><aside className="card p-5 space-y-3"><h2 className="font-semibold">Your recent questions</h2><p className="text-xs muted">Private history. Access is checked again when opened.</p>{history.error && <p className="error">{history.error.message}</p>}{history.data?.map(item => <div key={item.id} className="border-b border-[var(--border)] pb-3"><button className="text-left text-sm underline" disabled={busy} onClick={() => void run(async () => { const records = await api<typeof history.data>(`ai/conversations/${item.id}`); const messages = records![0].messages; setQuestion(messages.find(m => m.role === "user")?.content || ""); setResult(JSON.parse(messages.find(m => m.role === "assistant")!.content)); })}>{item.messages.find(m => m.role === "user")?.content}</button><Button variant="ghost" size="sm" disabled={busy} onClick={() => void run(async () => { await api(`ai/conversations/${item.id}`, { method: "DELETE" }); })}>Delete</Button></div>)}</aside></div>}
    {tab === "drafts" && <div className="grid gap-6 lg:grid-cols-2"><section className="card p-6"><h2 className="font-semibold mb-4">Create a draft</h2>
      <label>Assistant<select value={kind} onChange={e => { setKind(e.target.value as DraftInput["kind"]); setDraft(null); }}>{kinds.map(k => <option key={k} value={k}>{names[k]}</option>)}</select></label>
      <form key={kind} className="space-y-4 mt-4" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); const input: DraftInput = { kind, title: String(form.get("title")), brief: String(form.get("brief") || "") }; for (const field of ["jobTitle", "department", "experience", "location", "employmentType", "skills", "salaryRange", "responsibilities", "employeeId", "letterType", "jobDocumentId", "candidateId", "reviewId", "messageType"] as const) { const value = form.get(field); if (value) Object.assign(input, { [field]: String(value) }); } if (kind === "interview_summary") input.notes = notes; if (kind === "report_summary") input.report = { intent: String(form.get("report")) as "attendance_summary", scope: me.permissions.includes("attendance.read") ? "company" : "team", period: "month", moreThan: 3 }; void run(() => generate(input)); }}>
        <label>Draft title<input name="title" required maxLength={150} placeholder={names[kind]} /></label>
        {kind === "job_description" && ["jobTitle", "department", "experience", "location", "employmentType", "skills", "salaryRange", "responsibilities"].map(field => <label key={field}>{field.replace(/([A-Z])/g, " $1")}<input name={field} required={field === "jobTitle"} maxLength={field === "responsibilities" ? 2000 : field === "skills" ? 1000 : 100} /></label>)}
        {kind.startsWith("interview") && <label>Selected job description<select name="jobDocumentId" required><option value="">Select a saved job</option>{docs.data?.filter(d => d.kind === "job_description").map(d => <option key={d.id} value={d.id}>{d.title} ({d.status})</option>)}</select></label>}
        {kind === "letter" && <label>Letter type<select name="letterType" required>{letterKinds.map(k => <option key={k}>{k}</option>)}</select></label>}
        {(kind === "letter" || kind === "performance") && <label>Employee {kind === "performance" ? "(optional for generic goals)" : ""}<select name="employeeId" required={kind === "letter"}><option value="">Select employee</option>{people.data?.map(p => <option key={p.id} value={p.id}>{p.employeeCode} · {p.firstName} {p.lastName}</option>)}</select>{people.error && <span className="error">{people.error.message}</span>}</label>}
        {kind.startsWith("candidate_") && <label>Candidate<select name="candidateId" required><option value="">Select a candidate</option>{candidates.data?.map(c => <option key={c.id} value={c.id}>{c.name} · {c.job.title} · {c.stage.toLowerCase()}</option>)}</select>{candidates.error && <span className="error">{candidates.error.message}</span>}</label>}
        {kind === "candidate_message" && <label>Message<select name="messageType" required>{messageKinds.map(k => <option key={k}>{k}</option>)}</select></label>}
        {kind === "review_draft" && <label>Review<select name="reviewId" required><option value="">Select a review</option>{reviews.data?.filter(r => r.status === "PENDING_MANAGER").map(r => <option key={r.id} value={r.id}>{r.employee.employeeCode} · {r.employee.firstName} {r.employee.lastName} · {r.cycle.name}</option>)}</select></label>}
        {kind === "report_summary" && <label>Report (this month to date)<select name="report"><option value="attendance_summary">Attendance summary</option><option value="repeated_late">Repeated lateness, anonymized</option>{me.permissions.includes("employees.read") && <><option value="headcount">Active headcount</option><option value="departments">Department headcount</option></>}</select></label>}
        {kind === "interview_summary" && <div className="space-y-3">{notes.map((note, i) => <fieldset key={i} className="border rounded p-3 space-y-2"><legend>Interview note {i + 1}</legend>{(["question", "answer", "comments"] as const).map(field => <label key={field}>{field}<textarea rows={2} required={field === "question"} maxLength={field === "question" ? 500 : 1000} value={note[field]} onChange={e => setNotes(notes.map((n, j) => j === i ? { ...n, [field]: e.target.value } : n))} /></label>)}<label>Interviewer rating (1–5)<input type="number" min={1} max={5} required value={note.rating} onChange={e => setNotes(notes.map((n, j) => j === i ? { ...n, rating: Number(e.target.value) } : n))} /></label></fieldset>)}<Button type="button" variant="outline" disabled={notes.length >= 30} onClick={() => setNotes([...notes, { question: "", answer: "", rating: 3, comments: "" }])}>Add question</Button></div>}
        <label>Approved facts, designation, instructions or observations<textarea name="brief" rows={4} maxLength={6000} placeholder="Include only information approved for processing. Missing facts remain placeholders." /></label>
        <label className="flex gap-2 items-start text-sm"><input type="checkbox" required />I reviewed these inputs and they are appropriate for the company's configured AI provider.</label>
        <Button disabled={busy || !available}>{busy ? "Generating..." : "Generate"}</Button>
      </form>
    </section><section className="card p-6 space-y-4"><h2 className="font-semibold">Review and save</h2><p className="text-sm muted">Generated content is a draft. Human approval is required. Candidate and interview summaries never make hiring decisions, and review drafts never set a rating. An approved job description can be chosen when creating a job opening.</p>
      <label>Saved drafts<select value={draft?.id || ""} onChange={e => { const id = e.target.value; if (id) void run(async () => { setDraft(await api<Doc>(`ai/documents/${id}`)); setReviewed(false); }); }}><option value="">Select a draft</option>{docs.data?.map(d => <option key={d.id} value={d.id}>{d.title} · {d.status}</option>)}</select></label>{docs.error && <p className="error">{docs.error.message}</p>}
      {draft && <><p className="text-sm">{draft.status} · Revision {draft.revision}</p><label>Title<input value={draft.title} maxLength={150} onChange={e => { setDraft({ ...draft, title: e.target.value }); setReviewed(false); }} /></label><label>Draft content<textarea rows={20} value={draft.content} maxLength={20000} onChange={e => { setDraft({ ...draft, content: e.target.value }); setReviewed(false); }} /></label><label className="flex gap-2 text-sm"><input type="checkbox" checked={reviewed} onChange={e => setReviewed(e.target.checked)} />I have reviewed the facts and wording and approve this content.</label><div className="flex flex-wrap gap-2"><Button disabled={busy} onClick={() => void run(() => save("save"))}>Save edits</Button><Button variant="outline" disabled={busy || !reviewed} onClick={() => void run(() => save("approve"))}>Approve</Button>{draft.kind === "job_description" && <Button disabled={busy || draft.status !== "Approved"} onClick={() => void run(() => save("publish"))}>Publish internally</Button>}<Button variant="outline" disabled={busy || !available || !draft.input} onClick={() => void run(() => generate(draft.input!))}>Regenerate as new draft</Button><Button variant="outline" disabled={draft.status === "Draft"} onClick={() => { const url = URL.createObjectURL(new Blob([draft.content], { type: "text/plain;charset=utf-8" })); const a = document.createElement("a"); a.href = url; a.download = "approved-hr-document.txt"; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }}>Download approved text</Button></div></>}
    </section></div>}
    {tab === "settings" && config.data && <section className="card p-6 max-w-2xl"><h2 className="font-semibold mb-4">AI processing and retention</h2><p className="text-sm muted mb-4">Provider keys stay in deployment secrets. Conversation and draft content is encrypted. Retention applies to conversations, access logs and generated documents, including approved drafts.</p><form key={JSON.stringify(config.data)} className="space-y-4" onSubmit={event => { event.preventDefault(); const f = new FormData(event.currentTarget); void run(async () => { await api("ai/settings", { method: "PUT", body: JSON.stringify({ enabled: f.get("enabled") === "on", allowExternalProcessing: f.get("external") === "on", retentionDays: Number(f.get("days")) }) }); }); }}><label className="flex gap-2"><input type="checkbox" name="enabled" defaultChecked={config.data.enabled} />Enable AI generation</label><label className="flex gap-2"><input type="checkbox" name="external" defaultChecked={config.data.allowExternalProcessing} />Allow minimized context to be sent to the configured external provider</label><label>Retention days<input type="number" name="days" min={1} max={365} required defaultValue={config.data.retentionDays} /></label><p className="text-sm">Provider: {config.data.providerConfigured ? config.data.localProvider ? "Local" : "External" : "Not configured"}</p><Button disabled={busy}>Save settings</Button></form></section>}
    {tab === "logs" && <section className="card p-6"><h2 className="font-semibold mb-4">AI access log (latest 100)</h2>{logs.error && <p className="error">{logs.error.message}</p>}<div className="table-scroll"><table><thead><tr><th>Time</th><th>Intent</th><th>Sources</th><th>Status</th></tr></thead><tbody>{logs.data?.map(l => <tr key={l.id}><td>{new Date(l.timestamp).toLocaleString()}</td><td>{l.intent}</td><td>{l.dataSources.join(", ")}</td><td>{l.status}</td></tr>)}</tbody></table></div></section>}
  </>;
}
