ALTER TABLE "branches"
  ADD COLUMN "geofenceEnabled" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "latitude" DOUBLE PRECISION,
  ADD COLUMN "longitude" DOUBLE PRECISION,
  ADD COLUMN "radiusMeters" INTEGER NOT NULL DEFAULT 200;
